-- Add golfer-specific fields to profiles table
ALTER TABLE public.profiles
ADD COLUMN IF NOT EXISTS graduation_year INTEGER,
ADD COLUMN IF NOT EXISTS handicap NUMERIC(4,1),
ADD COLUMN IF NOT EXISTS home_course TEXT,
ADD COLUMN IF NOT EXISTS phone TEXT,
ADD COLUMN IF NOT EXISTS city TEXT,
ADD COLUMN IF NOT EXISTS state TEXT,
ADD COLUMN IF NOT EXISTS high_school TEXT,
ADD COLUMN IF NOT EXISTS club_team TEXT,
ADD COLUMN IF NOT EXISTS goal_division TEXT,
ADD COLUMN IF NOT EXISTS avatar_url TEXT;