-- Add manual-logo flag
ALTER TABLE public.colleges
ADD COLUMN IF NOT EXISTS logo_needs_manual BOOLEAN NOT NULL DEFAULT false;

-- Normalize all 2-letter state abbreviations to full names
UPDATE public.colleges SET state = CASE state
  WHEN 'AL' THEN 'Alabama'
  WHEN 'AK' THEN 'Alaska'
  WHEN 'AZ' THEN 'Arizona'
  WHEN 'AR' THEN 'Arkansas'
  WHEN 'CA' THEN 'California'
  WHEN 'CO' THEN 'Colorado'
  WHEN 'CT' THEN 'Connecticut'
  WHEN 'DE' THEN 'Delaware'
  WHEN 'DC' THEN 'District of Columbia'
  WHEN 'FL' THEN 'Florida'
  WHEN 'GA' THEN 'Georgia'
  WHEN 'HI' THEN 'Hawaii'
  WHEN 'ID' THEN 'Idaho'
  WHEN 'IL' THEN 'Illinois'
  WHEN 'IN' THEN 'Indiana'
  WHEN 'IA' THEN 'Iowa'
  WHEN 'KS' THEN 'Kansas'
  WHEN 'KY' THEN 'Kentucky'
  WHEN 'LA' THEN 'Louisiana'
  WHEN 'ME' THEN 'Maine'
  WHEN 'MD' THEN 'Maryland'
  WHEN 'MA' THEN 'Massachusetts'
  WHEN 'MI' THEN 'Michigan'
  WHEN 'MN' THEN 'Minnesota'
  WHEN 'MS' THEN 'Mississippi'
  WHEN 'MO' THEN 'Missouri'
  WHEN 'MT' THEN 'Montana'
  WHEN 'NE' THEN 'Nebraska'
  WHEN 'NV' THEN 'Nevada'
  WHEN 'NH' THEN 'New Hampshire'
  WHEN 'NJ' THEN 'New Jersey'
  WHEN 'NM' THEN 'New Mexico'
  WHEN 'NY' THEN 'New York'
  WHEN 'NC' THEN 'North Carolina'
  WHEN 'ND' THEN 'North Dakota'
  WHEN 'OH' THEN 'Ohio'
  WHEN 'OK' THEN 'Oklahoma'
  WHEN 'OR' THEN 'Oregon'
  WHEN 'PA' THEN 'Pennsylvania'
  WHEN 'RI' THEN 'Rhode Island'
  WHEN 'SC' THEN 'South Carolina'
  WHEN 'SD' THEN 'South Dakota'
  WHEN 'TN' THEN 'Tennessee'
  WHEN 'TX' THEN 'Texas'
  WHEN 'UT' THEN 'Utah'
  WHEN 'VT' THEN 'Vermont'
  WHEN 'VA' THEN 'Virginia'
  WHEN 'WA' THEN 'Washington'
  WHEN 'WV' THEN 'West Virginia'
  WHEN 'WI' THEN 'Wisconsin'
  WHEN 'WY' THEN 'Wyoming'
  WHEN 'PR' THEN 'Puerto Rico'
  WHEN 'VI' THEN 'U.S. Virgin Islands'
  WHEN 'GU' THEN 'Guam'
  WHEN 'AS' THEN 'American Samoa'
  WHEN 'MP' THEN 'Northern Mariana Islands'
  ELSE state
END
WHERE length(state) = 2;